"""initial schema

Revision ID: f7e6d85d8a52
Revises: 
Create Date: 2026-05-24 14:24:49.776825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f7e6d85d8a52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_account_name', sa.String(length=512), nullable=False),
    sa.Column('canonical_account_name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_account_name', name='uq_account_alias_source')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('diff_summary', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_file_sha256'), ['file_sha256'], unique=False)

    op.create_table('instrument_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('target_allocation_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(length=512), nullable=False),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('security_name', sa.String(length=1024), nullable=False),
    sa.Column('is_cash', sa.Boolean(), nullable=False),
    sa.Column('ticker', sa.String(length=64), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('asset_class', sa.String(length=128), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name', 'identifier', name='uq_account_identifier')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_account_name'), ['account_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_identifier'), ['identifier'], unique=False)

    op.create_table('order_import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_import_batches_file_sha256'), ['file_sha256'], unique=True)

    op.create_table('holding_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('investment_label', sa.String(length=1024), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_price_ccy', sa.String(length=16), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_ccy', sa.String(length=16), nullable=True),
    sa.Column('fx_rate', sa.Float(), nullable=True),
    sa.Column('last_price_pence', sa.Float(), nullable=True),
    sa.Column('value_gbp', sa.Float(), nullable=True),
    sa.Column('book_cost', sa.Float(), nullable=True),
    sa.Column('book_cost_ccy', sa.String(length=16), nullable=True),
    sa.Column('average_fx_rate', sa.Float(), nullable=True),
    sa.Column('book_cost_gbp', sa.Float(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_account_name', sa.String(length=512), nullable=True),
    sa.Column('canonical_account_name', sa.String(length=512), nullable=True),
    sa.Column('source_security_name', sa.String(length=1024), nullable=False),
    sa.Column('source_security_name_norm', sa.String(length=1024), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_account_name', 'source_security_name_norm', name='uq_instrument_alias_source_account_name')
    )
    op.create_table('instrument_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['instrument_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'instrument_id', name='uq_group_instrument')
    )
    op.create_table('instrument_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('price_gbp', sa.Float(), nullable=True),
    sa.Column('price_ccy', sa.String(length=16), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrument_quotes_instrument_id'), ['instrument_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_instrument_quotes_ticker'), ['ticker'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_import_batch_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('security_name', sa.String(length=1024), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_status', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=512), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('cost_proceeds_gbp', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('is_drip', sa.Boolean(), nullable=False),
    sa.Column('order_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('match_status', sa.String(length=32), nullable=True),
    sa.Column('match_method', sa.String(length=64), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_evidence', sqlite.JSON(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_import_batch_id'], ['order_import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_security_name'), ['security_name'], unique=False)
        batch_op.create_index('ux_orders_order_fingerprint', ['order_fingerprint'], unique=True)

    op.create_table('order_match_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('old_instrument_id', sa.Integer(), nullable=True),
    sa.Column('new_instrument_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sqlite.JSON(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['new_instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_match_audit')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ux_orders_order_fingerprint')
        batch_op.drop_index(batch_op.f('ix_orders_security_name'))
        batch_op.drop_index(batch_op.f('ix_orders_order_date'))
        batch_op.drop_index(batch_op.f('ix_orders_instrument_id'))

    op.drop_table('orders')
    with op.batch_alter_table('instrument_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrument_quotes_ticker'))
        batch_op.drop_index(batch_op.f('ix_instrument_quotes_instrument_id'))

    op.drop_table('instrument_quotes')
    op.drop_table('instrument_group_members')
    op.drop_table('instrument_aliases')
    op.drop_table('holding_snapshots')
    with op.batch_alter_table('order_import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_import_batches_file_sha256'))

    op.drop_table('order_import_batches')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_identifier'))
        batch_op.drop_index(batch_op.f('ix_instruments_account_name'))

    op.drop_table('instruments')
    op.drop_table('instrument_groups')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_file_sha256'))

    op.drop_table('import_batches')
    op.drop_table('account_aliases')
    # ### end Alembic commands ###
